version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ffmpeg/ffmpeg"
    versions:
    - "> 0.7.0"
  - dependency-name: svelte-check
    versions:
    - 1.1.28
    - 1.1.32
    - 1.1.33
    - 1.1.34
    - 1.1.35
    - 1.1.36
    - 1.2.3
    - 1.2.5
    - 1.2.6
    - 1.3.0
    - 1.4.0
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.3
    - 4.6.5
    - 4.6.6
    - 4.6.9
    - 4.7.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: svelte
    versions:
    - 3.31.2
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.1
    - 8.2.0
  - dependency-name: rollup
    versions:
    - 2.38.0
